[package]
name = "memcrs"
version = "0.0.1"
authors = ["Dariusz Ostolski <memc-rs@memc.rs>"]
edition = "2021"


[lib]
name = "memcrs"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byte-unit = "4.0.18"
bytes = "1.3.0"
clap = { version = "3.2.23", features = ["cargo"] }
dashmap = "5.4.0"
futures = "0.3.25"
futures-util = "0.3.25"
log = "0.4.17"
socket2 = { version = "0.4.7", features = ["all"] }
num_cpus = "1.15.0"
num-derive = "0.3.3"
num-traits = "0.2.15"
rand = { version = "0.8.5", features = ["small_rng"] }
serde = "1.0.152"
serde_derive = "1.0.152"
tracing = "0.1.37"
tracing-attributes = "0.1.23"
tracing-log = "0.1.3"
tracing-subscriber = { version = "0.3.16", default-features = false, features = ["std", "fmt"] }
tokio = { version = "1.24.0", features = ["full"] }
tokio-util = { version = "0.7.4", features = ["full"] }

[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemallocator = { version ="0.5.0", optional = true }